version: "3"

services:
  api:
    build: "./api"
    volumes:
      - ./api:/code
    ports:
      - 4000:4000

  www:
    build: "./www"
    volumes:
      - ./www:/code
    ports:
      - 1234:1234
    depends_on:
      - api
