schema {
  query: Query
  mutation: Mutation
}

type Query {
  words: [Word!]!
}

type Mutation {
  createWord(input: CreateWordInput!): Word!
  updateWord(id: ID!, input: CreateWordInput!): Word!
  deleteWord(id: ID!): Boolean!
}

input CreateWordInput {
  original: String!
  english: String!
}

type Word {
  id: ID!
  english: String!
  original: String!
}
