schema {
  query: Query
  mutation: Mutation
}

type Query {
  words(id: ID, limit: Int): [Word!]
}

type Mutation {
  createWord(input: CreateWordInput!): Word!
  updateWord(id: ID!, input: UpdateWordInput!): Word!
  deleteWord(id: ID!): Boolean!
}

input CreateWordInput {
  original: String!
  english: String!
}

input UpdateWordInput {
  original: String
  english: String
}

type Word {
  id: ID!
  english: String!
  original: String!
}
